version: '3'

services:
  app:
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
